before_script:
  - cd ./Front-End/angular-gitlab-ci-test
  - npm install

test:
  script: ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
