

build:
 stage: build
 image: trion/ng-cli

 before_script:
  - npm ci
  
 script:
  - cd ./Front-End/angular-gitlab-ci-test
  - ng build --prod
  
 artifacts:
  expire_in: 1 day
  paths:
   - dist/
   
 tags:
  - docker


test:karma:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - docker
