image: node:latest

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - dist/

stages:
  - setup
  - test
  - build
  - deploy


# install node packages
setup:
  stage: setup
  script:
    - cd Front-End/angular-gitlab-ci-test/
    - npm install

# run karma
tests:
  stage: test
  script:
    - cd Front-End/angular-gitlab-ci-test/
    - npm run test

# build dist
build:
  stage: build
  script:
    - cd Front-End/angular-gitlab-ci-test/
    - npm run build
  artifacts:
    paths:
      - dist/

